
OLLAMA_MODEL = "qwen2.5:7b"
OLLAMA_URL = "http://localhost:11434/api/generate"

EMOTION_ENABLED = True
EMOTION_CAMERA_INDEX = 0
EMOTION_CAPTURE_SECONDS = 5.0
EMOTION_SHOW_WINDOW = True
EMOTION_VISION_MODEL = ""
EMOTION_VISION_TIMEOUT = 60

PERCEPTION_VLM_MODEL = "gemini-3.1-flash-lite"
PERCEPTION_VLM_PERIOD = 8.0
PERCEPTION_VLM_TIMEOUT = 40

ADULT_AGE_THRESHOLD = 18
